
const importmapscriptelement = document.createElement('script');
importmapscriptelement.type = 'importmap';
importmapscriptelement.textContent = JSON.stringify({
  "imports": {
    "@codemirror/basic-setup": "https://ga.jspm.io/npm:@codemirror/basic-setup@0.20.0/dist/index.js",
    "@codemirror/commands": "https://ga.jspm.io/npm:@codemirror/commands@0.20.0/dist/index.js",
    "@codemirror/lang-javascript": "https://ga.jspm.io/npm:@codemirror/lang-javascript@6.0.0/dist/index.js",
    "@codemirror/state": "https://ga.jspm.io/npm:@codemirror/state@0.20.1/dist/index.js",
    "@codemirror/view": "https://ga.jspm.io/npm:@codemirror/view@0.20.7/dist/index.js",
    "@material/mwc-button": "https://ga.jspm.io/npm:@material/mwc-button@0.26.1/mwc-button.js",
    "@material/mwc-dialog": "https://ga.jspm.io/npm:@material/mwc-dialog@0.26.1/mwc-dialog.js",
    "@material/mwc-drawer": "https://ga.jspm.io/npm:@material/mwc-drawer@0.26.1/mwc-drawer.js",
    "@material/mwc-fab": "https://ga.jspm.io/npm:@material/mwc-fab@0.26.1/mwc-fab.js",
    "@material/mwc-icon-button": "https://ga.jspm.io/npm:@material/mwc-icon-button@0.26.1/mwc-icon-button.js",
    "@material/mwc-linear-progress": "https://ga.jspm.io/npm:@material/mwc-linear-progress@0.26.1/mwc-linear-progress.js",
    "@material/mwc-list": "https://ga.jspm.io/npm:@material/mwc-list@0.26.1/mwc-list.js",
    "@material/mwc-list/mwc-list-item": "https://ga.jspm.io/npm:@material/mwc-list@0.26.1/mwc-list-item.js",
    "@material/mwc-select": "https://ga.jspm.io/npm:@material/mwc-select@0.26.1/mwc-select.js",
    "@material/mwc-snackbar": "https://ga.jspm.io/npm:@material/mwc-snackbar@0.26.1/mwc-snackbar.js",
    "@material/mwc-textfield": "https://ga.jspm.io/npm:@material/mwc-textfield@0.26.1/mwc-textfield.js",
    "@material/mwc-top-app-bar": "https://ga.jspm.io/npm:@material/mwc-top-app-bar@0.26.1/mwc-top-app-bar.js",
    "near-api-js": "https://ga.jspm.io/npm:near-api-js@0.45.1/lib/browser-index.js"
  },
  "scopes": {
    "https://ga.jspm.io/": {
      "@codemirror/autocomplete": "https://ga.jspm.io/npm:@codemirror/autocomplete@0.20.3/dist/index.js",
      "@codemirror/language": "https://ga.jspm.io/npm:@codemirror/language@0.20.2/dist/index.js",
      "@codemirror/lint": "https://ga.jspm.io/npm:@codemirror/lint@0.20.3/dist/index.js",
      "@codemirror/search": "https://ga.jspm.io/npm:@codemirror/search@0.20.1/dist/index.js",
      "@codemirror/state": "https://ga.jspm.io/npm:@codemirror/state@6.0.1/dist/index.js",
      "@codemirror/view": "https://ga.jspm.io/npm:@codemirror/view@6.0.2/dist/index.js",
      "@lezer/common": "https://ga.jspm.io/npm:@lezer/common@0.16.1/dist/index.js",
      "@lezer/highlight": "https://ga.jspm.io/npm:@lezer/highlight@0.16.0/dist/index.js",
      "@lezer/javascript": "https://ga.jspm.io/npm:@lezer/javascript@1.0.0/dist/index.es.js",
      "@lezer/lr": "https://ga.jspm.io/npm:@lezer/lr@1.0.0/dist/index.js",
      "@lit/reactive-element": "https://ga.jspm.io/npm:@lit/reactive-element@1.3.2/reactive-element.js",
      "@lit/reactive-element/decorators/custom-element.js": "https://ga.jspm.io/npm:@lit/reactive-element@1.3.2/decorators/custom-element.js",
      "@lit/reactive-element/decorators/event-options.js": "https://ga.jspm.io/npm:@lit/reactive-element@1.3.2/decorators/event-options.js",
      "@lit/reactive-element/decorators/property.js": "https://ga.jspm.io/npm:@lit/reactive-element@1.3.2/decorators/property.js",
      "@lit/reactive-element/decorators/query-all.js": "https://ga.jspm.io/npm:@lit/reactive-element@1.3.2/decorators/query-all.js",
      "@lit/reactive-element/decorators/query-assigned-elements.js": "https://ga.jspm.io/npm:@lit/reactive-element@1.3.2/decorators/query-assigned-elements.js",
      "@lit/reactive-element/decorators/query-assigned-nodes.js": "https://ga.jspm.io/npm:@lit/reactive-element@1.3.2/decorators/query-assigned-nodes.js",
      "@lit/reactive-element/decorators/query-async.js": "https://ga.jspm.io/npm:@lit/reactive-element@1.3.2/decorators/query-async.js",
      "@lit/reactive-element/decorators/query.js": "https://ga.jspm.io/npm:@lit/reactive-element@1.3.2/decorators/query.js",
      "@lit/reactive-element/decorators/state.js": "https://ga.jspm.io/npm:@lit/reactive-element@1.3.2/decorators/state.js",
      "@material/animation/animationframe": "https://ga.jspm.io/npm:@material/animation@14.0.0-canary.53b3cad2f.0/animationframe.js",
      "@material/base/foundation": "https://ga.jspm.io/npm:@material/base@14.0.0-canary.53b3cad2f.0/foundation.js",
      "@material/base/foundation.js": "https://ga.jspm.io/npm:@material/base@14.0.0-canary.53b3cad2f.0/foundation.js",
      "@material/dialog/constants.js": "https://ga.jspm.io/npm:@material/dialog@14.0.0-canary.53b3cad2f.0/constants.js",
      "@material/dialog/foundation.js": "https://ga.jspm.io/npm:@material/dialog@14.0.0-canary.53b3cad2f.0/foundation.js",
      "@material/dom/events.js": "https://ga.jspm.io/npm:@material/dom@14.0.0-canary.53b3cad2f.0/events.js",
      "@material/dom/keyboard": "https://ga.jspm.io/npm:@material/dom@14.0.0-canary.53b3cad2f.0/keyboard.js",
      "@material/dom/keyboard.js": "https://ga.jspm.io/npm:@material/dom@14.0.0-canary.53b3cad2f.0/keyboard.js",
      "@material/dom/ponyfill.js": "https://ga.jspm.io/npm:@material/dom@14.0.0-canary.53b3cad2f.0/ponyfill.js",
      "@material/drawer/constants.js": "https://ga.jspm.io/npm:@material/drawer@14.0.0-canary.53b3cad2f.0/constants.js",
      "@material/drawer/dismissible/foundation.js": "https://ga.jspm.io/npm:@material/drawer@14.0.0-canary.53b3cad2f.0/dismissible/foundation.js",
      "@material/drawer/modal/foundation.js": "https://ga.jspm.io/npm:@material/drawer@14.0.0-canary.53b3cad2f.0/modal/foundation.js",
      "@material/floating-label/foundation.js": "https://ga.jspm.io/npm:@material/floating-label@14.0.0-canary.53b3cad2f.0/foundation.js",
      "@material/line-ripple/foundation.js": "https://ga.jspm.io/npm:@material/line-ripple@14.0.0-canary.53b3cad2f.0/foundation.js",
      "@material/list/constants": "https://ga.jspm.io/npm:@material/list@14.0.0-canary.53b3cad2f.0/constants.js",
      "@material/list/constants.js": "https://ga.jspm.io/npm:@material/list@14.0.0-canary.53b3cad2f.0/constants.js",
      "@material/list/typeahead.js": "https://ga.jspm.io/npm:@material/list@14.0.0-canary.53b3cad2f.0/typeahead.js",
      "@material/menu-surface/constants": "https://ga.jspm.io/npm:@material/menu-surface@14.0.0-canary.53b3cad2f.0/constants.js",
      "@material/menu-surface/constants.js": "https://ga.jspm.io/npm:@material/menu-surface@14.0.0-canary.53b3cad2f.0/constants.js",
      "@material/menu-surface/foundation": "https://ga.jspm.io/npm:@material/menu-surface@14.0.0-canary.53b3cad2f.0/foundation.js",
      "@material/menu-surface/foundation.js": "https://ga.jspm.io/npm:@material/menu-surface@14.0.0-canary.53b3cad2f.0/foundation.js",
      "@material/menu/constants.js": "https://ga.jspm.io/npm:@material/menu@14.0.0-canary.53b3cad2f.0/constants.js",
      "@material/menu/foundation.js": "https://ga.jspm.io/npm:@material/menu@14.0.0-canary.53b3cad2f.0/foundation.js",
      "@material/mwc-base/aria-property.js": "https://ga.jspm.io/npm:@material/mwc-base@0.26.1/aria-property.js",
      "@material/mwc-base/base-element.js": "https://ga.jspm.io/npm:@material/mwc-base@0.26.1/base-element.js",
      "@material/mwc-base/form-element.js": "https://ga.jspm.io/npm:@material/mwc-base@0.26.1/form-element.js",
      "@material/mwc-base/observer.js": "https://ga.jspm.io/npm:@material/mwc-base@0.26.1/observer.js",
      "@material/mwc-base/utils.js": "https://ga.jspm.io/npm:@material/mwc-base@0.26.1/utils.js",
      "@material/mwc-floating-label/mwc-floating-label-directive.js": "https://ga.jspm.io/npm:@material/mwc-floating-label@0.26.1/mwc-floating-label-directive.js",
      "@material/mwc-icon/mwc-icon.js": "https://ga.jspm.io/npm:@material/mwc-icon@0.26.1/mwc-icon.js",
      "@material/mwc-line-ripple/mwc-line-ripple-directive.js": "https://ga.jspm.io/npm:@material/mwc-line-ripple@0.26.1/mwc-line-ripple-directive.js",
      "@material/mwc-list/mwc-list-foundation.js": "https://ga.jspm.io/npm:@material/mwc-list@0.26.1/mwc-list-foundation.js",
      "@material/mwc-list/mwc-list.js": "https://ga.jspm.io/npm:@material/mwc-list@0.26.1/mwc-list.js",
      "@material/mwc-menu/mwc-menu.js": "https://ga.jspm.io/npm:@material/mwc-menu@0.26.1/mwc-menu.js",
      "@material/mwc-notched-outline/mwc-notched-outline.js": "https://ga.jspm.io/npm:@material/mwc-notched-outline@0.26.1/mwc-notched-outline.js",
      "@material/mwc-ripple/mwc-ripple.js": "https://ga.jspm.io/npm:@material/mwc-ripple@0.26.1/mwc-ripple.js",
      "@material/mwc-ripple/ripple-handlers.js": "https://ga.jspm.io/npm:@material/mwc-ripple@0.26.1/ripple-handlers.js",
      "@material/notched-outline/foundation.js": "https://ga.jspm.io/npm:@material/notched-outline@14.0.0-canary.53b3cad2f.0/foundation.js",
      "@material/ripple/foundation.js": "https://ga.jspm.io/npm:@material/ripple@14.0.0-canary.53b3cad2f.0/foundation.js",
      "@material/select/foundation.js": "https://ga.jspm.io/npm:@material/select@14.0.0-canary.53b3cad2f.0/foundation.js",
      "@material/snackbar/foundation.js": "https://ga.jspm.io/npm:@material/snackbar@14.0.0-canary.53b3cad2f.0/foundation.js",
      "@material/textfield/foundation.js": "https://ga.jspm.io/npm:@material/textfield@14.0.0-canary.53b3cad2f.0/foundation.js",
      "@material/top-app-bar/constants.js": "https://ga.jspm.io/npm:@material/top-app-bar@14.0.0-canary.53b3cad2f.0/constants.js",
      "@material/top-app-bar/standard/foundation.js": "https://ga.jspm.io/npm:@material/top-app-bar@14.0.0-canary.53b3cad2f.0/standard/foundation.js",
      "base-x": "https://ga.jspm.io/npm:base-x@3.0.9/src/index.js",
      "blocking-elements": "https://ga.jspm.io/npm:blocking-elements@0.1.1/dist/blocking-elements.js",
      "bn.js": "https://ga.jspm.io/npm:bn.js@5.2.0/lib/bn.js",
      "borsh": "https://ga.jspm.io/npm:borsh@0.7.0/lib/index.js",
      "bs58": "https://ga.jspm.io/npm:bs58@4.0.1/index.js",
      "buffer": "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/browser/buffer.js",
      "capability": "https://ga.jspm.io/npm:capability@0.2.5/index.js",
      "capability/es5": "https://ga.jspm.io/npm:capability@0.2.5/es5.js",
      "crelt": "https://ga.jspm.io/npm:crelt@1.0.5/index.es.js",
      "crypto": "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/browser/crypto.js",
      "depd": "https://ga.jspm.io/npm:depd@2.0.0/lib/browser/index.js",
      "error-polyfill": "https://ga.jspm.io/npm:error-polyfill@0.1.3/index.js",
      "http-errors": "https://ga.jspm.io/npm:http-errors@1.8.1/index.js",
      "inherits": "https://ga.jspm.io/npm:inherits@2.0.4/inherits_browser.js",
      "js-sha256": "https://ga.jspm.io/npm:js-sha256@0.9.0/src/sha256.js",
      "lit": "https://ga.jspm.io/npm:lit@2.2.6/index.js",
      "lit-element/lit-element.js": "https://ga.jspm.io/npm:lit-element@3.2.0/lit-element.js",
      "lit-html": "https://ga.jspm.io/npm:lit-html@2.2.6/lit-html.js",
      "lit-html/async-directive.js": "https://ga.jspm.io/npm:lit-html@2.2.6/async-directive.js",
      "lit-html/directive.js": "https://ga.jspm.io/npm:lit-html@2.2.6/directive.js",
      "lit-html/directives/class-map.js": "https://ga.jspm.io/npm:lit-html@2.2.6/directives/class-map.js",
      "lit-html/directives/if-defined.js": "https://ga.jspm.io/npm:lit-html@2.2.6/directives/if-defined.js",
      "lit-html/directives/live.js": "https://ga.jspm.io/npm:lit-html@2.2.6/directives/live.js",
      "lit-html/directives/style-map.js": "https://ga.jspm.io/npm:lit-html@2.2.6/directives/style-map.js",
      "lit/async-directive.js": "https://ga.jspm.io/npm:lit@2.2.6/async-directive.js",
      "lit/decorators.js": "https://ga.jspm.io/npm:lit@2.2.6/decorators.js",
      "lit/directive.js": "https://ga.jspm.io/npm:lit@2.2.6/directive.js",
      "lit/directives/class-map.js": "https://ga.jspm.io/npm:lit@2.2.6/directives/class-map.js",
      "lit/directives/if-defined.js": "https://ga.jspm.io/npm:lit@2.2.6/directives/if-defined.js",
      "lit/directives/live.js": "https://ga.jspm.io/npm:lit@2.2.6/directives/live.js",
      "lit/directives/style-map.js": "https://ga.jspm.io/npm:lit@2.2.6/directives/style-map.js",
      "mustache": "https://ga.jspm.io/npm:mustache@4.2.0/mustache.js",
      "o3": "https://ga.jspm.io/npm:o3@1.0.3/index.js",
      "process": "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/browser/process-production.js",
      "safe-buffer": "https://ga.jspm.io/npm:safe-buffer@5.2.1/index.js",
      "setprototypeof": "https://ga.jspm.io/npm:setprototypeof@1.2.0/index.js",
      "statuses": "https://ga.jspm.io/npm:statuses@1.5.0/index.js",
      "style-mod": "https://ga.jspm.io/npm:style-mod@4.0.0/src/style-mod.js",
      "text-encoding-utf-8": "https://ga.jspm.io/npm:text-encoding-utf-8@1.0.2/lib/encoding.lib.js",
      "toidentifier": "https://ga.jspm.io/npm:toidentifier@1.0.1/index.js",
      "tslib": "https://ga.jspm.io/npm:tslib@2.4.0/tslib.es6.js",
      "tweetnacl": "https://ga.jspm.io/npm:tweetnacl@1.0.3/nacl-fast.js",
      "u3": "https://ga.jspm.io/npm:u3@0.1.1/index.js",
      "w3c-keyname": "https://ga.jspm.io/npm:w3c-keyname@2.2.4/index.es.js",
      "wicg-inert": "https://ga.jspm.io/npm:wicg-inert@3.1.2/dist/inert.esm.js"
    },
    "https://ga.jspm.io/npm:@codemirror/autocomplete@6.0.2/": {
      "@codemirror/language": "https://ga.jspm.io/npm:@codemirror/language@6.1.0/dist/index.js"
    },
    "https://ga.jspm.io/npm:@codemirror/lang-javascript@6.0.0/": {
      "@codemirror/autocomplete": "https://ga.jspm.io/npm:@codemirror/autocomplete@6.0.2/dist/index.js",
      "@codemirror/language": "https://ga.jspm.io/npm:@codemirror/language@6.1.0/dist/index.js",
      "@lezer/common": "https://ga.jspm.io/npm:@lezer/common@1.0.0/dist/index.js"
    },
    "https://ga.jspm.io/npm:@codemirror/language@6.1.0/": {
      "@lezer/common": "https://ga.jspm.io/npm:@lezer/common@1.0.0/dist/index.js",
      "@lezer/highlight": "https://ga.jspm.io/npm:@lezer/highlight@1.0.0/dist/index.js"
    },
    "https://ga.jspm.io/npm:@lezer/highlight@1.0.0/": {
      "@lezer/common": "https://ga.jspm.io/npm:@lezer/common@1.0.0/dist/index.js"
    },
    "https://ga.jspm.io/npm:@lezer/javascript@1.0.0/": {
      "@lezer/highlight": "https://ga.jspm.io/npm:@lezer/highlight@1.0.0/dist/index.js"
    },
    "https://ga.jspm.io/npm:@lezer/lr@1.0.0/": {
      "@lezer/common": "https://ga.jspm.io/npm:@lezer/common@1.0.0/dist/index.js"
    },
    "https://ga.jspm.io/npm:http-errors@1.8.1/": {
      "depd": "https://ga.jspm.io/npm:depd@1.1.2/lib/browser/index.js"
    }
  }
});
document.currentScript.after(importmapscriptelement);
